version: '2'
services:
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    expose:
      - "3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  redis:
    image: redis
  web:
    image: drupal:7.53
    volumes: 
      - ./drupal-7.53:/var/www/html
    ports:
      - "5000:80"
    links:
      - redis
      - db
